### ISSUE TITLE
I run this app alaws show “no face found”，I do not know reason

### ISSUE THREAD

**Issue by niebiao** [jackweiwang/Android-FaceDetection-UltraNet-MNN#7] opened 2020-04-22 06:45 UTC

**Comment by ridoy-ai** [comment] 2020-04-22 14:21
I am also facing the same issue, after running the app, when the input image is selected, pressing "Do Facedetect" button showing “no face found” text! What could be the reason behind it?

**Comment by jackweiwang** [comment] 2020-04-22 14:32
Thanks, I will fixed in no time

**Comment by ridoy-ai** [comment] 2020-04-23 11:45
@jackweiwang , the issue is fixed now. Thank you for your quick response, appreciate it.

**Comment by jackweiwang** [comment] 2020-04-23 11:56
My pleasure :)

**Closed as completed** 2020-04-23 11:57 UTC
